spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    url: jdbc:mariadb://localhost:3306/DBP
    #insert your db password
    password: n70704650
  jpa:
    properties:
      hibernate:
        show-sql: 'true'
        format_sql: 'true'
    hibernate:
      ddl-auto: update
  devtools:
    restart:
      enabled: 'true'
    livereload:
      enabled: 'true'
  servlet:
    multipart:
      max-file-size: 20MB

server:
  servlet:
    session:
      timeout: 1800 # ?? ???? ?? (??: ?)


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: DEBUG